//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Forecasts = new HashSet<Forecast>();
        }
    
        public int LocationId { get; set; }
        public Nullable<System.DateTime> NextUpdate { get; set; }
        public string GeonameId { get; set; }
        public string CountryName { get; set; }
        public string AdminName1 { get; set; }
        public string GeoName { get; set; }
    
        public virtual ICollection<Forecast> Forecasts { get; set; }
    }
}
